#!/bin/bash
input="./factionstest1.txt"
while IFS=":" read -r col1 col2 col3 col4
do
echo {\"_id\":\"$col1\",\"name\":\"$col2\",\"permission\":{\"default\":0,\"5izWgADOTEOz6xAL\":3},\"type\":\"faction\",\"data\":{\"description\":\"$col4\",\"type\":\"Underworld\",\"tier\":\"$col3\",\"goal_1\":\"\",\"goal_1_clock_max\":8,\"goal_2\":\"\",\"goal_2_clock_max\":8,\"turf\":\"\",\"assets\":\"\",\"quirks\":\"\",\"notables\":\"\",\"allies\":\"\",\"enemies\":\"\",\"situation\":\"\",\"goal_clock\":0,\"hold\":{\"value\":1,\"max\":2,\"max_default\":2,\"name_default\":\"BITD.Hold\",\"name\":\"BITD.Hold\"},\"status\":{\"value\":[4],\"max\":7,\"max_default\":7,\"name_default\":\"BITD.Status\",\"name\":\"BITD.Status\"}},\"flags\":{},\"img\":\"systems/runners-in-the-shadows/styles/assets/icons/Icon.3_04.png\",\"notes\":\"\",\"effects\":[]}

# {"_id":"nLX4OTV9rsMP6i6M","name":"ZNEWFACTION","type":"faction","img":"icons/svg/item-bag.svg","data":{"description":"","type":"","tier":"0","goal_1":"","goal_1_clock_max":"4","goal_2":"","goal_2_clock_max":"4","turf":"","assets":"","quirks":"","notables":"","allies":"","enemies":"","situation":"","goal_clock":0,"notes":"","hold":{"value":[1],"max":2,"max_default":2,"name_default":"BITD.Hold","name":"BITD.Hold"},"status":{"value":[4],"max":7,"max_default":7,"name_default":"BITD.Status","name":"BITD.Status"},"goal_1_clock_value":"0","goal_2_clock_value":"0"},"effects":[],"folder":null,"sort":0,"permission":{"default":0,"bKqGeVModevqdmzQ":3},"flags":{}}
#echo {"name":\"$col1\","type":"faction","img":"icons/svg/item-bag.svg","data":{"description":\"$col3\","type":"","tier":\"$col2\","goal_1":"","goal_1_clock_max":"4","goal_2":"","goal_2_clock_max":"4","turf":"","assets":"","quirks":"","notables":"","allies":"","enemies":"","situation":"","goal_clock":0,"notes":"","hold":{"value":[1],"max":2,"max_default":2,"name_default":"BITD.Hold","name":"BITD.Hold"},"status":{"value":[4],"max":7,"max_default":7,"name_default":"BITD.Status","name":"BITD.Status"},"goal_1_clock_value":"0","goal_2_clock_value":"0"},"effects":[],"folder":null,"sort":0,"permission":{"default":0,"5izWgADOTEOz6xAL":3},"flags":{},"_id":""}
#echo {"name":\"$col1\","type":"faction","img":"icons/svg/item-bag.svg","data":{"description":\"$col3\","type":"","tier":\"$col2\","goal_1":"","goal_1_clock_max":0,"goal_2":"","goal_2_clock_max":0,"turf":"","assets":"","quirks":"","notables":"","allies":"","enemies":"","situation":"","goal_clock":0,"notes":"","hold":{"value":[1],"max":2,"max_default":2,"name_default":"BITD.Hold","name":"BITD.Hold"},"status":{"value":[4],"max":7,"max_default":7,"name_default":"BITD.Status","name":"BITD.Status"}},"effects":[],"folder":null,"sort":0,"permission":{"default":0,"bKqGeVModevqdmzQ":3},"flags":{}}
done < "$input"
